server:
  port: 8081

spring:
  application:
    name: calendar
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.57.66.84:40910/calendar?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wjsdudwo
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
